// solid/src/App.jsx
import { createMemo, createEffect, onCleanup } from "solid-js";
import { createStore } from "solid-js/store";

const setFocus = (el) => setTimeout(() => el.focus());

export default () => {
  const STORAGE_KEY = "todos-solid";

  const [filter, setfilter] = createSignal("all");
  const [editingIndex, setEditingIndex] = createSignal(null);
  const [todos, setTodos] = createStore(JSON.parse(localStorage.getItem(STORAGE_KEY)) || []);
  createEffect(() => localStorage.setItem(STORAGE_KEY, JSON.stringify(todos)));

  const filters = {
    all: (todos) => todos,
    active: (todos) => todos.filter((todo) => !todo.completed),
    completed: (todos) => todos.filter((todo) => todo.completed)
  };

  const filterTodos = () => filters[filter()](todos());
  const remainingCount = createMemo(() => filters.active(todos).length);

  const clearCompleted = ()      => setTodos((t) => todos = filters.active(todos));
  const toggleAll      = (checked) => setTodos((todo) => todo.completed = checked);
  const toggle         = (toggleIndex, checked) => setTodos(todos().map((todo, index) => index === toggleIndex ? { ...todo, completed: checked } : todo));
  const remove         = (index) => setTodos((t) => t.filter((item) => item.id !== todoId))
  const edit           = (index) => setEditingIndex(todoId);
  const cancel         = ()      => setEditingIndex();
  const create         = (title) => setTodos([...todos(), { id: Date.now(), title, completed: false }]);
  const updateView     = ()      => setState("filter", location.hash.slice(2) || "all");// filter = location.hash.slice(2) || "all";
  const update         = (title) => setState("todos", (item) => item.id === todo.id, todo),//(title ? todos[editingIndex].title = title : remove(editingIndex), editingIndex = null);

  window.addEventListener("hashchange", updateView);
  onCleanup(() => window.removeEventListener("hashchange", updateView));

  return (
    <section class="todoapp">
      <header class="header">
        <h1>todos</h1>
        <input class="new-todo" autofocus placeholder="What needs to be done?" required pattern=".*\S+.*"
          onkeydown={e => e.key ==='Enter' && e.target.checkValidity() && create(e.target.value.trim())}
          onkeyup={e => e.key ==='Enter' ? e.target.value = '' : ''}>
      </header>

      <Show when={todos().length}>
        <section class="main">
          <input id="toggle-all" class="toggle-all" type="checkbox" checked={!remainingCount()} onchange={e => toggleAll(e.target.checked)}>
          <label for="toggle-all">Mark all as complete</label>

          <ul class="todo-list">
            <For each={filterTodos()}>
              {(todo, index) => (
                <li class="todo" classList={{ completed: todo.completed, editing: editingIndex() === index }}>

                  <div class="view">
                    <input class="toggle" type="checkbox" checked={todo.completed} onchange={e => toggle(index, e.target.checked)}>
                    <label ondblclick={[edit, index]}>{todo.title}</label>
                    <button class="destroy" onclick={[remove, index]} />
                  </div>

                  <Show when={editingIndex() === index}>
                    <input class="edit" value={todo.title} use:setFocus
                      onkeydown={e =>
                        e.key ==='Enter' ? update(e.target.value.trim()) :
                        e.key ==='Escape' && cancel()}
                      onblur={e => update(e.target.value.trim())}>
                  </Show>
                </li>
              )}
            </For>
          </ul>
        </section>

        <footer class="footer">
          <span class="todo-count">
            <strong>{remainingCount()}</strong>{" "}{remainingCount() === 1 ? " item " : " items "} left
          </span>
          <ul class="filters">
            <li><a href="#/all" classList={{selected: filter() === 'all'}}>All</a></li>
            <li><a href="#/active" classList={{selected: filter() 'active'}>Active</a></li>
            <li><a href="#/completed" classList={{selected: filter() 'completed'}>Completed</a></li>
          </ul>
          <Show when={remainingCount()}>
            <button class="clear-completed" onclick={clearCompleted}>Clear completed</button>
          </Show>
        </footer>
      </Show>
    </section>
  );
};

// react/src/App.jsx
/* eslint-disable react/prop-types */
import { useState, useEffect, useMemo } from "react";
import clsx from "clsx";

const ESCAPE_KEY = 27;
const ENTER_KEY = 13;

const setFocus = (el) => el?.focus();

const LOCAL_STORAGE_KEY = "todos-react";
function useLocalStore(value) {
  // load stored todos on init
  const stored = localStorage.getItem(LOCAL_STORAGE_KEY),
    [store, setStore] = useState(stored ? JSON.parse(stored) : value);

  // JSON.stringify creates deps on every iterable field
  useEffect(
    () => localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(store)),
    [store]
  );
  return [store, setStore];
}

const TodoItem = ({
  todo,
  store,
  toggle,
  setEditing,
  removeTodo,
  save,
  doneEditing
}) => {
  return (
    <li
      className={clsx("todo", {
        editing: store.editingTodoId === todo.id,
        completed: todo.completed
      })}
    >
      <div className="view">
        <input
          className="toggle"
          type="checkbox"
          checked={todo.completed}
          onChange={(e) => toggle(todo.id, e)}
        />
        <label onDoubleClick={() => setEditing(todo.id)}>{todo.title}</label>
        <button className="destroy" onClick={() => removeTodo(todo.id)} />
      </div>
      {store.editingTodoId === todo.id && (
        <input
          className="edit"
          defaultValue={todo.title}
          onBlur={(e) => save(todo.id, e)}
          onKeyUp={(e) => doneEditing(todo.id, e)}
          ref={setFocus}
        />
      )}
    </li>
  );
};

const TodoApp = () => {
  const [store, setStore] = useLocalStore({
      counter: 1,
      todos: [],
      showMode: "all",
      editingTodoId: null
    }),
    remainingCount = useMemo(
      () =>
        store.todos.length -
        store.todos.filter((todo) => todo.completed).length,
      [store.todos]
    ),
    filterList = (todos) => {
      if (store.showMode === "active")
        return todos.filter((todo) => !todo.completed);
      else if (store.showMode === "completed")
        return todos.filter((todo) => todo.completed);
      else return todos;
    },
    removeTodo = (todoId) =>
      setStore((s) => ({
        ...s,
        todos: s.todos.filter((item) => item.id !== todoId)
      })),
    editTodo = (todo) =>
      setStore((s) => ({
        ...s,
        todos: s.todos.map((item) => {
          if (item.id !== todo.id) return item;
          return { ...item, ...todo };
        })
      })),
    clearCompleted = () =>
      setStore((s) => ({
        ...s,
        todos: s.todos.filter((todo) => !todo.completed)
      })),
    toggleAll = (completed) =>
      setStore((s) => ({
        ...s,
        todos: s.todos.map((todo) => {
          if (todo.completed === completed) return todo;
          return { ...todo, completed };
        })
      })),
    setEditing = (todoId) => setStore((s) => ({ ...s, editingTodoId: todoId })),
    addTodo = ({ target, keyCode }) => {
      const title = target.value.trim();
      if (keyCode === ENTER_KEY && title) {
        setStore((s) => ({
          ...s,
          todos: [
            { title, id: store.counter, completed: false },
            ...store.todos
          ],
          counter: store.counter + 1
        }));
        target.value = "";
      }
    },
    save = (todoId, { target: { value } }) => {
      const title = value.trim();
      if (store.editingTodoId === todoId && title) {
        editTodo({ id: todoId, title });
        setEditing();
      }
    },
    toggle = (todoId, { target: { checked } }) =>
      editTodo({ id: todoId, completed: checked }),
    doneEditing = (todoId, e) => {
      if (e.keyCode === ENTER_KEY) save(todoId, e);
      else if (e.keyCode === ESCAPE_KEY) setEditing();
    };

  const locationHandler = () =>
    setStore((s) => ({ ...s, showMode: location.hash.slice(2) || "all" }));

  useEffect(() => {
    window.addEventListener("hashchange", locationHandler);
    return () => window.removeEventListener("hashchange", locationHandler);
  });

  return (
    <section className="todoapp">
      <header className="header">
        <h1>todos</h1>
        <input class="new-todo" autofocus placeholder="What needs to be done?" required pattern=".*\S+.*"
          onkeydown={e => e.key ==='Enter' && e.target.checkValidity() && create(e.target.value.trim())}
          onkeyup={e => e.key ==='Enter' ? e.target.value = '' : ''}>
        />
      </header>

      {store.todos.length > 0 && (
        <>
          <section className="main">
            <input
              id="toggle-all"
              className="toggle-all"
              type="checkbox"
              checked={!remainingCount}
              onChange={({ target: { checked } }) => toggleAll(checked)}
            />
            <label htmlFor="toggle-all" />
            <ul className="todo-list">
              {filterList(store.todos).map((todo) => (
                <TodoItem
                  key={todo.id}
                  {...{
                    todo,
                    store,
                    toggle,
                    setEditing,
                    removeTodo,
                    save,
                    doneEditing
                  }}
                />
              ))}
            </ul>
          </section>

          <footer className="footer">
            <span className="todo-count">
              <strong>{remainingCount}</strong>{" "}
              {remainingCount === 1 ? " item " : " items "} left
            </span>
            <ul className="filters">
              <li>
                <a
                  href="#/"
                  className={clsx({ selected: store.showMode === "all" })}
                >
                  All
                </a>
              </li>
              <li>
                <a
                  href="#/active"
                  className={clsx({ selected: store.showMode === "active" })}
                >
                  Active
                </a>
              </li>
              <li>
                <a
                  href="#/completed"
                  className={clsx({ selected: store.showMode === "completed" })}
                >
                  Completed
                </a>
              </li>
            </ul>
            {remainingCount !== store.todos.length && (
              <button className="clear-completed" onClick={clearCompleted}>
                Clear completed
              </button>
            )}
          </footer>
        </>
      )}
    </section>
  );
};

export default TodoApp;
